### ISSUE TITLE
safari&iosで動かない

### ISSUE THREAD

**Issue by nakazye** [bokuweb/slack-list-ja#1]
index.s20632行目のエラー

> [Error] ReferenceError: Can't find variable: fetch
>     componentDidMount
>     notifyAll
>     close
>     closeAll
>     perform
>     batchedMountComponentIntoNode
>     perform
>     batchedUpdates
>     batchedUpdates
>     _renderNewRootComponent
>     ReactMount__renderNewRootComponent
>     _renderSubtreeIntoContainer
>     render
>     React_render
>     （anonymous 関数）
>     s
>     e
>     （anonymous 関数）

**Comment by bokuweb** [comment]
@nakazye thanks.
