### ISSUE TITLE
ruby-on-rails-jpを削除していただけたらと思います。

### ISSUE THREAD

**Issue by daisukeokaoss** [bokuweb/slack-list-ja#64]
すいません。ruby-on-rails-jpを閉じることにしたので、ruby-on-rails-jpを削除していただけたらと思います。
「追加」がプルリクでいいことはわかっているんですが、「削除」がプルリクでいいのかがよくわからなかったので、issue出しました。

**Comment by bokuweb** [comment]
消しときますね

**Comment by bokuweb** [comment]
done

**Comment by daisukeokaoss** [comment]
ありがとうございます！！
